### ISSUE TITLE
Edge.sendEvent callback doesn't deliver all information

### ISSUE THREAD

**Issue by mdonke** [adobe/aepsdk-react-native#143] opened 2022-02-16 10:44 UTC
I'm having issues extracting the Edge Tracking Response in my RN code.
While native code receives the data correctly, the `Edge.sendEvent` callback in RN does not give all information.

### Expected Behaviour
Edge Tracking Event response is available in RN code

### Actual Behaviour
Cropped response

```
[{"type":"activation:pull","payload":[{"destinationId":"XXX","type":"profileLookup","alias":"XXX"}]}]
```

#### Steps to Reproduce

1. Define an Edge Segment which qualifies if below event is fired
2. Ingest an experience event from the app
3. Extract response

#### Platform and Version
Android @adobe/react-native-aepedge@1.0.0-beta.1

#### Sample Code that illustrates the problem
```
    Edge.sendEvent(experienceEvent).then(function (value) {
      console.log("event response:" + JSON.stringify(value))
```

#### Logs taken while reproducing problem

Looking at `adb logcat` I can see the expected response coming. (Look at "segments" below)

```
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK: Edge - NetworkResponseHandler - Received server response:
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK: {
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:   "requestId": "d68d1e17-a119-4cb4-8e74-b6c12152d2ba",
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:   "handle": [
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:     {
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:       "payload": [
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:         {
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:           "type": "profileLookup",
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:           "destinationId": "XXX",
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:           "alias": "XXXX",
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:           "segments": [
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:             {
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:               "id": "54617704-6afc-42c8-8be5-4255a03cd6b9"
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:             },
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:             {
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:               "id": "88122b80-8081-4caa-9e46-b9bc0d021857"
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:             }
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:           ]
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:         }
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:       ],
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:       "type": "activation:pull",
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:       "eventIndex": 0
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:     }
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK:   ]
02-16 10:34:11.831 15800 15893 D AdobeExperienceSDK: }
```

**Comment by mdonke** [comment] 2022-02-16 14:03
The issue is located in [RCTAEPEdgeMapUtil](https://github.com/adobe/aepsdk-react-native/blob/main/packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeMapUtil.java#L63) where you don't handle the incoming (weird) ArrayList/HashMap data structure for "segments".

Can you please fix this?

**Comment by cacheung** [comment] 2022-02-16 18:40
@mdonke, thanks for reporting.  We will look into it.

Calise Cheung
Mobile Engineer

**Comment by cacheung** [comment] 2022-02-18 19:28
Hi @mdonke,
     We narrowed down the issue for Android platform and working on a fix.
     iOS has different implementation, could you check iOS and let us know if you see the issue there with the same response?
      
Thanks,
Calise Cheung
Mobile Engineer

**Comment by mdonke** [comment] 2022-02-22 08:43
Yes, just verified: its working fine on iOS.

**Comment by cacheung** [comment] 2022-03-11 21:30
Hi @mdonke, @adobe/react-native-aepedge@1.0.0-beta.2 is released which addresses this issue.  
Please let us know if it resolves the problem.

Thanks,
Calise

**Comment by cacheung** [comment] 2022-03-21 19:08
Hi @mdonke, have you got chance to try the beta.2 and see the issue is resolved?

**Comment by cacheung** [comment] 2022-03-31 21:18
Closing this for now, you can open a new ticket if still see the issue.

**Closed by cacheung** 2022-03-31 21:18 UTC

**Comment by mdonke** [comment] 2022-04-13 07:49
Upgraded to 1.0.0 and I confirm its working now. Thanks for your efforts!
